--DROP TABLE BOARD;

--CREATE TABLE BOARD(
--    ID INT(10) NULL AUTO_INCREMENT PRIMARY KEY,
--    CATEGORY VARCHAR(20),
--    TITLE VARCHAR(50),
--    DESCRIPTION VARCHAR(2000),
--    REG_USER VARCHAR(20),
--    REG_DATE VARCHAR(20),
--    VIEW_COUNT INT(10)
--);

